//importing db 
const db=require('../util/database');

const Cart = require('./cart');

module.exports = class Product {
  constructor(id, title, imageUrl, description, price) {
    this.id = id;
    this.title = title;
    this.imageUrl = imageUrl;
    this.description = description;
    this.price = price;
  }

  //It should save data to database
  save() {

    //the item in () should be in same order as in our db.We can ignore ID as it is autogenerated
    //to safely insert values we use "VALUES" to avoid SQL injection
    
    //is a second argument we pass to execute with the values that will be injected instead of these
    //question marks,so the order of the elements we add here to this array is the order of arguments here

    return db.execute('INSERT INTO products (title, price ,description,imageUrl) VALUES (?, ?, ?, ?)',
    [this.title,this.price,this.description,this.imageUrl])
  }

  static deleteById(id) {
    
  }

  static fetchAll() {
    return db.execute('SELECT * FROM products');
  }

  static findById(id) {
    return db.execute('SELECT * FROM products WHERE products.id = ?', [id]);
  }
};
